spring:
  application:
    name: BookManager

  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.H2Dialect
  h2:
    console.enabled: true
  jackson:
    serialization:
      indent-output: true

openlibrary:
  bookUrl: "https://openlibrary.org/isbn/"
  coverUrl: "https://covers.openlibrary.org/b/isbn/"

logging:
  level:
    bswe.swm2: DEBUG