replicaCount: 1

image:
  repository: ghcr.io/fhburgenland-bswe/swm2-ws2024-kp-hahnl-bookmanager
  pullPolicy: Always
  tag: "latest"

imagePullSecrets: [ name: ghcr-credentials ]
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  automount: true
  annotations: {}
  name: ""

podAnnotations: {}
podLabels: {}
podSecurityContext: {}
securityContext: {}

service:
  type: ClusterIP
  port: 8080

ingress:
  enabled: true
  className: ""
  annotations:
    external-dns.alpha.kubernetes.io/provider: public
    external-dns.alpha.kubernetes.io/target: 178.63.69.250,2a01:4f8:121:14e2:100:3:3:1
    cert-manager.io/cluster-issuer: cluster-issuer-muehlbachler-xyz
  hosts:
    - host: bookmanager.hahnl.bswe.fh-burgenland.muehlbachler.xyz
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: fh-bswe-hahnl-bookmanager-tls
      hosts:
        - bookmanager.hahnl.bswe.fh-burgenland.muehlbachler.xyz

resources:
   limits:
     cpu: 250m
     memory: 512Mi
   requests:
     cpu: 100m
     memory: 256Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80

volumes: []

volumeMounts: []

nodeSelector: {}

tolerations: []

affinity: {}
