---
name: Main Build

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    name: Build Jar File
    strategy:
      matrix:
        java-version: ["21"]
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "${{ matrix.java-version }}"
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew bootJar
      - uses: actions/upload-artifact@v4
        with:
          name: spring-boot-jar
          path: build/libs/bookmanager.jar