---
name: Pull Request

on:
  pull_request:

permissions:
  contents: read

jobs:
  check:
    runs-on: ubuntu-latest
    name: Check Code
    strategy:
      matrix:
        java-version: [ "21" ]
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "${{ matrix.java-version }}"
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew check

  test:
    runs-on: ubuntu-latest
    name: Unit Tests
    strategy:
      matrix:
        java-version: ["21"]
    steps:
      - uses: step-security/harden-runner@c6295a65d1254861815972266d5933fd6e532bdf # v2.11.1
        with:
          egress-policy: audit
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: "${{ matrix.java-version }}"
          cache: 'gradle'
      - uses: gradle/actions/setup-gradle@v4
      - run: ./gradlew test

  security:
    runs-on: ubuntu-latest
    name: SBOM & Vulnerability Scan
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Install Syft
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Install Grype
        run: |
          curl -sSfL https://raw.githubusercontent.com/anchore/grype/main/install.sh | sh -s -- -b /usr/local/bin
      - name: Generate SBOM
        run: syft . -o syft-json > sbom.json
      - name: Run Grype Scan
        run: |
          grype sbom:sbom.json -c config/grype/grype-config.yml --file grype-report.txt